engforyou/engforyou/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("learning_english.urls")),
    path('users/', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls', namespace="quiz")),
    path('survey/', include('survey.urls', namespace="survey")),
    path('recomendations/', include('recomendations.urls', namespace="recomendations")),
]

engforyou/quiz/urls.py
from django.urls import path
from .views import (
    QiuzListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
)

app_name = 'quiz'

urlpatterns = [
    path('', QiuzListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),


]

engforyou/survey/urls.py
from django.urls import path
from .views import survey_view, save_learning_profile
app_name = 'survey'

urlpatterns = [
    path('', survey_view, name='survey-view'),
    path('save/', save_learning_profile, name='save_learning_profile'),
]

engforyou/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    
    path('password-reset/',
         PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    
]

engforyou/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime


class User(AbstractUser):
    age = models.PositiveSmallIntegerField(
        verbose_name='возраст',
        null=True,
        blank=True
    )
    
    
    
    

engforyou/users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин или email', widget=forms.TextInput(attrs={'id': 'username', 'required': True}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'id': 'password', 'required': True}))
    

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': "Имя",
            'last_name': "Фамилия",
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))


    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'age']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'age': 'Возраст'
            
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'age': forms.NumberInput(attrs={'class': 'form-input'})
        }
        
    def clean_age(self):
        age = self.cleaned_data['age']
        if age is not None and age <= 0:
            raise forms.ValidationError('Возраст должен быть положительным числом')
        return age

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

engforyou/users/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView
from django.urls import reverse, reverse_lazy

from survey.models import LearningStyle

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name =  'users/login.html'
   
class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    def get_success_url(self):
        path = self.request.GET.get('path')
        if path:
            return f"{reverse_lazy('users:login')}?next={path}"
        return reverse_lazy('users:login')
    
class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['learning_style'] = LearningStyle.objects.get(user=self.object)
        return context

engforyou/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'learning_english/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'learning_english/img/logo_white_bg.png' %}" type="image/png">
    <title>Вход</title>
    <style>
        body {
            height: auto;
            background-color: #F7EDE8;
            margin: 5rem;
            display: flex;
            justify-content: center;
            align-items: center;
            @media (max-width: 811px) {
                margin: 1rem;
                height: auto;
              }
        }
        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
            @media (max-width: 811px) {
                margin-bottom: 1rem;
              }
        }
        h2 {
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            margin-bottom: 10px;
        }
        label {
            margin-bottom: 5px;
            text-align: left;
        }
        input {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            padding: 10px;
            background-color: #CD4631;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background-color: #A83B2A;
        }
        .messages {
            margin-top: 15px;
            color: #CD4631;
            font-size: 12px;
        }
        a {
            text-decoration:underline;
        }
        a:hover {
            color: #CD4631;
        }
    </style>
</head>
<body>

    <div class="container">
        <h2>Вход</h2>
        <form method="post">
            {% csrf_token %}
            
            <div class="messages">
                {% for error in form.non_field_errors %}
                    <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            {% for f in form %}
            <label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
            <div class="form-error">{{ f.errors }}</div>
            {% endfor %}
            <button type="submit">Войти</button>
        </form>
        <a href="{% url 'users:register' %}">Зарегистрироваться</a>
        <div class="messages">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    </div>
</body>
</html>

engforyou/users/templates/users/password_change_done.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'learning_english/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'learning_english/img/logo_white_bg.png' %}" type="image/png">
    <title>Пароль изменен</title>
    <style>
        body {
            height: auto;
            background-color: #F7EDE8;
            margin: 5rem;
            display: flex;
            justify-content: center;
            align-items: center;
            @media (max-width: 811px) {
                margin: 1rem;
                height: auto;
              }
        }
        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
            @media (max-width: 811px) {
                margin-bottom: 1rem;
              }
        }
        h2 {
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            margin-bottom: 10px;
        }
        label {
            margin-bottom: 5px;
            text-align: left;
        }
        input {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            padding: 10px;
            background-color: #CD4631;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background-color: #A83B2A;
        }
        .messages {
            margin-top: 15px;
            color: #CD4631;
            font-size: 12px;
        }
        a {
            text-decoration:underline;
        }
        a:hover {
            color: #CD4631;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
    </div>
</body>
</html>

engforyou/users/templates/users/password_change_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'learning_english/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'learning_english/img/logo_white_bg.png' %}" type="image/png">
    <title>Профиль</title>
    <style>
        body {
            height: auto;
            background-color: #F7EDE8;
            margin: 5rem;
            display: flex;
            justify-content: center;
            align-items: center;
            @media (max-width: 811px) {
                margin: 1rem;
                height: auto;
              }
        }
        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
            @media (max-width: 811px) {
                margin-bottom: 1rem;
              }
        }
        h2 {
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            margin-bottom: 10px;
        }
        label {
            margin-bottom: 5px;
            text-align: left;
        }
        input {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            padding: 10px;
            background-color: #CD4631;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background-color: #A83B2A;
        }
        .messages {
            margin-top: -1rem;
            color: #CD4631;
            margin-bottom: 1rem;
        }
        a {
            text-decoration:underline;
        }
        a:hover {
            color: #CD4631;
        }
        .my-btn-outline-black:hover {
            border: 2px solid black;
            background-color: white;
            color: black;
            box-shadow: none;
          }
    </style>
</head>
<body>
    
            <div class="container">

                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                    <div class="messages">
                        {% for error in f.errors  %}
                                <div class="error-message">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                
                    <p><button type="submit" class="btn my-btn-outline-black">Изменить пароль</button></p>
                </form>
            </div>
         
          

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

engforyou/users/templates/users/password_reset_complete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'learning_english/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'learning_english/img/logo_white_bg.png' %}" type="image/png">
    <title>Пароль изменен</title>
    <style>
        body {
            height: auto;
            background-color: #F7EDE8;
            margin: 5rem;
            display: flex;
            justify-content: center;
            align-items: center;
            @media (max-width: 811px) {
                margin: 1rem;
                height: auto;
              }
        }
        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
            @media (max-width: 811px) {
                margin-bottom: 1rem;
              }
        }
        h2 {
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            margin-bottom: 10px;
        }
        label {
            margin-bottom: 5px;
            text-align: left;
        }
        input {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            padding: 10px;
            background-color: #CD4631;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background-color: #A83B2A;
        }
        .messages {
            margin-top: 15px;
            color: #CD4631;
            font-size: 12px;
        }
        a {
            text-decoration:underline;
        }
        a:hover {
            color: #CD4631;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. Используйте его для <a href="{% url 'users:login' %}?next=/">входа в систему</a>.</p>
    </div>
</body>
</html>

engforyou/users/templates/users/password_reset_confirm.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'learning_english/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'learning_english/img/logo_white_bg.png' %}" type="image/png">
    <title>Профиль</title>
    <style>
        body {
            height: auto;
            background-color: #F7EDE8;
            margin: 5rem;
            display: flex;
            justify-content: center;
            align-items: center;
            @media (max-width: 811px) {
                margin: 1rem;
                height: auto;
              }
        }
        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
            @media (max-width: 811px) {
                margin-bottom: 1rem;
              }
        }
        h2 {
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            margin-bottom: 10px;
        }
        label {
            margin-bottom: 5px;
            text-align: left;
        }
        input {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            padding: 10px;
            background-color: #CD4631;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background-color: #A83B2A;
        }
        .messages {
            margin-top: -1rem;
            color: #CD4631;
            margin-bottom: 1rem;
        }
        a {
            text-decoration:underline;
        }
        a:hover {
            color: #CD4631;
        }
        .my-btn-outline-black:hover {
            border: 2px solid black;
            background-color: white;
            color: black;
            box-shadow: none;
          }
    </style>
</head>
<body>
    
            <div class="container">

                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                    <div class="messages">
                        {% for error in f.errors  %}
                                <div class="error-message">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                
                    <p><button type="submit" class="btn my-btn-outline-black">Сохранить</button></p>
                </form>
            </div>
         
          

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

engforyou/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

engforyou/users/templates/users/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'learning_english/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'learning_english/img/logo_white_bg.png' %}" type="image/png">
    <title>Профиль</title>
    <style>
        .container {
            
            padding-top: 2rem;
            border-radius: 10px;
            width: 300px;
            text-align: center;
            @media (max-width: 811px) {
                margin-bottom: 1rem;
              }
        }
        select {
          width: 200px; /* Ширина */
          margin-bottom: 0.5rem;
          padding: 10px; /* Отступы */
          font-size: 16px; /* Размер шрифта */
          color: #333; /* Цвет текста */
          background-color: white; /* Цвет фона */
          border: 1px solid #e1d7d2; /* Цвет границы */
          border-radius: 5px; /* Закругление углов */
          appearance: none; /* Убираем стандартный стиль */
          background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10"><polygon points="0,0 10,0 5,5" fill="%23333"/></svg>'); /* Стрелка */
          background-repeat: no-repeat;
          background-position: right 10px center; /* Позиция стрелки */
          background-size: 10px; /* Размер стрелки */
      }
      
      select:focus {
          border-color: #f7ede8; /* Цвет границы при фокусе */
          outline: none; /* Убираем стандартный контур */
      }
        h2 {
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            margin-bottom: 10px;
        }
        label {
            margin-bottom: 5px;
            text-align: left;
        }
        input {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        
        
        .messages {
            margin-top: 15px;
            color: #CD4631;
            font-size: 12px;
        }
        .my-btn-outline-black:hover {
            border: 2px solid black;
            background-color: white;
            color: black;
            box-shadow: none;
          }
          .change-pass {
            text-decoration:underline;
        }
        .change-pass:hover {
            color: #CD4631;
        }
        .admin {
          margin-bottom: 10rem;
          text-align: center;
          align-self: center;
        }
        .survey-res {
          padding-top: 2rem;
          text-align: center;
        }
        
    </style>
</head>
<body>
    <div class="wrapper">
        <header class="header">
          {% include 'learning_english/includes/header-top.html' %}
          <div class="header-middle">
            <div class="row">
              <div class="col-2 shapes">
                <img src="{% static 'learning_english/img/shape-swirl.svg' %}" alt="">
              </div>
              <div class="col-8 container-col">
                <div class="row first-text">Мой</div>
                <div class="row second-text about-header">профиль</div>
              </div>
              <div class="col-2 shapes p-0">
                <img class="stars" src="{% static 'learning_english/img/shape-stars.svg' %}" alt="">
              </div>
            </div>
          </div>
          
          </header>

          <main>
             <div class="survey-res">
                {% if learning_style %}
                    <div class="h5">Ваши основные стили обучения: {{learning_style.primary_style}} + {{learning_style.secondary_style}}</div>
                    <div>Визуал {{learning_style.visual_percent}}%</div>
                    <div>Аудиал {{learning_style.audio_percent}}%</div>
                    <div>Читатель/писатель {{learning_style.reader_percent}}%</div>
                    <div class="mb-2">Кинестетик {{learning_style.kinesthetic_percent}}%</div>                    
                {% endif %}
                <div><a class="change-pass survey-btn" href="{% url 'survey:survey-view' %}">Определить мой стиль обучения</a></div>
              </div>
            <div class="container">

             
             

                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                
                    <p><button type="submit" class="btn my-btn-outline-black">Сохранить</button></p>
                </form>
                {% if user.is_superuser %}
            <a class="change-pass admin" href="{% url 'admin:index' %}">Перейти в админ панель</a>
          {% endif %}
                <a class="change-pass" href="{% url 'users:password_change' %}">Сменить пароль</a>

              </div>
             
           
          </main>
          {% include 'learning_english/includes/footer.html' %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>