engforyou/engforyou/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("learning_english.urls")),
    path('users/', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls', namespace="quiz")),
    path('survey/', include('survey.urls', namespace="survey")),
    path('recomendations/', include('recomendations.urls', namespace="recomendations")),
]

engforyou/learning_english/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("times", views.times, name="times"),
    path("speaking", views.speaking, name="speaking"),
    path("verbs", views.verbs, name="verbs"),
    path("topics", views.topics, name="topics"),
    path("topics/<int:pk>/", views.detail_topic, name='detail_topic'),
    path("lessons", views.lessons, name="lessons"),
    path('lessons/<int:pk>/', views.detail_lesson, name='detail_lesson'),
    path('random/', views.random_url, name='random_url'),
    
]

engforyou/quiz/urls.py
from django.urls import path
from .views import (
    QiuzListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
)

app_name = 'quiz'

urlpatterns = [
    path('', QiuzListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),


]

engforyou/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    
    path('password-reset/',
         PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    
]

engforyou/learning_english/models.py
from django.db import models
from users.models import User

class Lesson(models.Model):
    title = models.TextField()
    subtitle = models.TextField()
    article = models.TextField()

    class Meta:
        managed = True
        db_table = 'lessons'

    def __str__(self):
        return self.title


class SpeakingTheme(models.Model):
    title = models.TextField()
    question_1 = models.TextField()
    question_2 = models.TextField()
    question_3 = models.TextField()
    
    class Meta:
        managed = True
        

    def __str__(self):
        return self.title
    
class Verb(models.Model):
    infinitive = models.TextField()
    second_form = models.TextField()
    third_form = models.TextField()
    translate = models.TextField()
    
    class Meta:
        managed = True
        

    def __str__(self):
        return self.infinitive
    

class Topic(models.Model):
    title = models.TextField()
    theme = models.TextField()
    article = models.TextField()
    question_1 = models.TextField()
    question_2 = models.TextField()
    question_3 = models.TextField()
    question_4 = models.TextField()
    question_5 = models.TextField()
    translate_1 = models.TextField()
    translate_2 = models.TextField()
    translate_3 = models.TextField()
    translate_4 = models.TextField()
    translate_5 = models.TextField()

    class Meta:
        managed = True
        db_table = 'topics'

    def __str__(self):
        return self.title
    
    def theme_as_title(self):
        return self.theme.split('-')


class Comment(models.Model):

    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    lesson = models.ForeignKey('Lesson', on_delete=models.CASCADE, null=True, blank=True)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    answer = models.TextField(null=True)

    def __str__(self):
        return self.text[:20]
    

engforyou/learning_english/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Комментарий',
            
            
        }
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-input'}),
            
        }

engforyou/learning_english/views.py
from lib2to3.fixes.fix_input import context
from pydoc_data.topics import topics


from django.contrib.auth.decorators import login_required


from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse

from .models import Topic, Lesson, SpeakingTheme, Verb, Comment
from .forms import CommentForm

import random

def random_url(request):
    urls = ['topics', 'lessons', 'about', 'speaking', 'verbs', 'times']
    random_url = random.choice(urls)
    return redirect(reverse(random_url))


def index(request):
    topics_list = Topic.objects.all()
    context = {"topics_list": topics_list}
    return render(request, "learning_english/index.html", context)

def about(request):
    return render(request, "learning_english/about.html")

def times(request):
    return render(request, "learning_english/times.html")

def verbs(request):
    verbs_list = Verb.objects.all()
    context = {"verbs_list": verbs_list}
    return render(request, "learning_english/verbs.html", context)
    

def speaking(request):
    speaking_list = SpeakingTheme.objects.all()
    random_theme = SpeakingTheme.objects.order_by('?')[0]
    context = {"speaking_list": speaking_list, "random_theme": random_theme}
    return render(request, "learning_english/speaking.html", context)

def topics(request):
    topics_list = Topic.objects.all()
    context = {"topics_list": topics_list}
    return render(request, "learning_english/topics.html", context)

def detail_topic(request, pk):
    topic = Topic.objects.get(pk=pk)
    comments = Comment.objects.filter(topic=topic).order_by('-created_at')
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.topic = topic
            comment.save()
            return redirect(reverse('detail_topic', args=[pk]))
    else:
        comment_form = CommentForm()
    return render(request, 'learning_english/topic.html',
                  {'topic': topic,
                   'topic_id':topic.id,
                   'comments': comments, 
                   'form': comment_form})
    


def lessons(request):
    lessons_list = Lesson.objects.all()
    context = {"lessons_list": lessons_list}
    return render(request, "learning_english/lessons.html", context)

def detail_lesson(request, pk):
    lesson = Lesson.objects.get(pk=pk)
    comments = Comment.objects.filter(lesson=lesson).order_by('-created_at')
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.lesson = lesson
            comment.save()
            return redirect(reverse('detail_lesson', args=[pk]))
    else:
        comment_form = CommentForm()
    return render(request, 'learning_english/lesson.html',
                  {'lesson': lesson,
                   'lesson_id':lesson.id,
                   'comments': comments, 
                   'form': comment_form})

def detail(request, topic_id):
    return HttpResponse("You're looking at topic %s." % topic_id)




@login_required
def add_comment(request, lesson_id=None, topic_id=None):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            if lesson_id:
                comment.lesson_id = lesson_id
            if topic_id:
                comment.topic_id = topic_id
            comment.save()
            return redirect('detail_lesson' if lesson_id else 'detail_topic')
    else:
        form = CommentForm()
    return render(request, 'add_comment.html', {'form': form})

engforyou/learning_english/templates/learning_english/includes/comments.html
<style>
    form {
      display: flex;
      flex-direction: column;
      margin-bottom: 10px;
  }
  label {
      margin-bottom: 5px;
      text-align: left;
  }
  input {
      padding: 10px;
      margin-bottom: 15px;
      border: 1px solid #ccc;
      border-radius: 5px;
  }
  button {
      padding: 10px;
      background-color: #CD4631;
      color: #fff;
      border: none;
      border-radius: 5px;
      cursor: pointer;
  }
  button:hover {
      background-color: #A83B2A;
  }
  .messages {
      margin-top: 15px;
      color: #CD4631;
      font-size: 12px;
  }


  </style>

<div class="commets-block">
    <h4>Комментарии:</h4>
    <div class="all-comments">

      {% if comments %}
        <ul>
        {% for comment in comments %}
          <li> <div class="comment-created_at">
            ({{comment.created_at}})

          </div>
            {{ comment.author.username }} : {{ comment.text }}</li>

            {% if comment.answer %}
            <li class="answer-full">
              <div class="answer-by-admin">
                Ответ администратора:&nbsp; 
              </div>
              <div class="colored">{{ comment.answer }}</div> 
            </li>
            {% endif %}
        {% endfor %}
        </ul> 
        {% else %}
        <ul>
          <li>Нет комментариев.</li>
        </ul>
        
      {% endif %}
    </div>
    

    <div class="add-comment">
      {% if user.is_authenticated %}  

      <h4>Добавить комментарий:</h4>
    <form method="post">
      {% csrf_token %}
      <div class="messages">
          {% for error in form.non_field_errors %}
              <div class="error-message">{{ error }}</div>
          {% endfor %}
      </div>
      {% for f in form %}
      {{ f }}
      <div class="form-error">{{ f.errors }}</div>
      {% endfor %}
      <button type="submit">Добавить</button>
    </form>
  {% endif %} 
    </div>

    
</div>

engforyou/learning_english/templates/learning_english/includes/footer.html
{% load static %}
<footer class="footer">
    <div class="footer-content">
      <div class="row">

        <div class="col-8">
          <div class="row">
            <div class="col footer-logo">
              <img src="{% static 'learning_english/img/logo.svg' %}" alt="">
              Начни прямо сейчас
            </div>
            
          </div>
        </div>
        <div class="col-4">
          <div class="row footer-row">
            <div class="col-6 footer-links">
              <a href="{% url 'about' %}" class="footer-link">О нас</a>
              <a href="{% url 'lessons' %}" class="footer-link colored-footer">Грамматика</a>
              <a href="{% url 'speaking' %}" class="footer-link">Говорение</a>
            </div>
            <div class="col-6 footer-links">
              <a href="{% url 'topics' %}" class="footer-link colored-footer">Тексты</a>
              <a href="{% url 'times' %}" class="footer-link">Времена</a>
              <a href="{% url 'verbs' %}" class="footer-link colored-footer">Глаголы</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="footer-bottom">
      <hr>

      <div class="footer-bottom-text">
        <pre class="light-text">Разработан в ходе обучения в университете. </pre>
        
       <div class="colored">Eng for You</div> 
        
      </div>
    </div>
  </footer>

engforyou/learning_english/templates/learning_english/includes/header-top.html
{% load static %}
<div class="header-top">
    <div class="row">
      <div class="col-md-6">
        <ul class="menu">
          <li class="menu-item sm-logo">
            <div class="logo">
              <img src="{% static 'learning_english/img/logo.svg' %}" alt="">
            </div>
          </li>
          <li class="menu-item">
            <a href="{% url 'index' %}">Главная</a>
          </li>
          <li class="menu-item">
            <a class="menu-link" href="{% url 'about' %}">О нас</a>
          </li>
          <li class="menu-item with-space">
            <div class="lessons">Уроки</div>
            <div class="dropdown">
              <div class="btn" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% static 'learning_english/img/ic-arrow-down.svg' %}" alt="">
              </div>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'topics' %}">Тексты</a></li>
                <li><a class="dropdown-item" href="{% url 'times' %}">Времена</a></li>
                <li><a class="dropdown-item" href="{% url 'lessons' %}">Грамматика</a></li>
                <li><a class="dropdown-item" href="{% url 'speaking' %}">Говорение</a></li>
                <li><a class="dropdown-item" href="{% url 'verbs' %}">Глаголы</a></li>
                <li><a class="dropdown-item" href="{% url 'quiz:main-view' %}">Тесты</a></li>
              </ul>
            </div> 
          </li>
          <li class="menu-item">
            
          </li>
        </ul> 
      </div>
      <div class="col-md-6 buttons-auth"> 
        <ul class="buttons-auth">
          {% if user.is_authenticated %}
            <li>
              <div class="username"><a class="username" href="{% url 'users:profile' %}">Welcome, {{ user.first_name }}!</a></div>
            </li>
            <li>
              <a href="{% url 'users:logout' %}">

              <button class="btn my-btn-outline-black">Выйти</button></a>
            </li>
            
            {% else %}
          <li>
            
            <a href="{% url 'users:register'%}?path={{ request.path }} ">
            <div class="btn my-btn-outline">
              Регистрация</div></a>
          </li>
          <li>
            <a href="{% url 'users:login' %}?next={{ request.path }}">

            <button class="btn my-btn-outline-black">Войти</button></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>